[tool.black]
line-length = 120
target-version = ['py39']
include = '\.pyx?$'
extend-exclude = '''
^/(fts-venv|venv|env|.env|.venv)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 100
skip_glob = ["fts-venv/*", "venv/*", "env/*", ".env/*", ".venv/*"]

[tool.pytest]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "--verbose -ra --cov"
